# https://cloud.google.com/appengine/docs/standard/python/config/appref
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: build/index.html
    secure: always
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    secure: always
    upload: build/(.*)
