"""
Constant value for valid country names.
"""

VALID_COUNTRY_NAMES = frozenset(
    {
        "Zimbabwe",
        "Singapore",
        "Sierra Leone",
        "Niger",
        "Seychelles",
        "Malaysia",
        "Bangladesh",
        "Sweden",
        "Gabon",
        "Iceland",
        "United Kingdom",
        "Angola",
        "Jamaica",
        "Kazakhstan",
        "Finland",
        "Cambodia",
        "Guyana",
        "Ghana",
        "United States",
        "Sudan",
        "Taiwan",
        "Japan",
        "Montenegro",
        "Latvia",
        "Iran",
        "Australia",
        "Botswana",
        "Morocco",
        "Tajikistan",
        "Grenada",
        "Central African Republic",
        "Somalia",
        "Cyprus",
        "Cape Verde",
        "Yemen",
        "Israel",
        "South Korea",
        "Nicaragua",
        "Belgium",
        "Congo",
        "Bhutan",
        "Mali",
        "Ecuador",
        "Oman",
        "Burkina Faso",
        "Slovenia",
        "Lebanon",
        "Mauritius",
        "Tunisia",
        "Malta",
        "Egypt",
        "Sri Lanka",
        "Swaziland",
        "Laos",
        "Comoros",
        "Portugal",
        "Moldova",
        "Slovakia",
        "Venezuela",
        "Czech Republic",
        "Western Sahara",
        "Colombia",
        "Lithuania",
        "Uruguay",
        "Suriname",
        "India",
        "Mexico",
        "Kyrgyzstan",
        "Zambia",
        "Georgia",
        "Algeria",
        "Paraguay",
        "Namibia",
        "Spain",
        "Saint Lucia",
        "China",
        "Peru",
        "Albania",
        "Democratic Republic of Congo",
        "Jordan",
        "Liechtenstein",
        "Timor",
        "Equatorial Guinea",
        "Libya",
        "Antigua and Barbuda",
        "Djibouti",
        "New Zealand",
        "Luxembourg",
        "Senegal",
        "Syria",
        "Thailand",
        "Mauritania",
        "Cameroon",
        "Haiti",
        "Uganda",
        "Ukraine",
        "Chad",
        "Turkey",
        "Sao Tome and Principe",
        "Netherlands",
        "Papua New Guinea",
        "Germany",
        "Liberia",
        "Malawi",
        "Myanmar",
        "Brunei",
        "Philippines",
        "Gambia",
        "Serbia",
        "Mozambique",
        "Andorra",
        "Indonesia",
        "Afghanistan",
        "Austria",
        "Uzbekistan",
        "Estonia",
        "United Arab Emirates",
        "Bulgaria",
        "Fiji",
        "Argentina",
        "Iraq",
        "Togo",
        "Panama",
        "Mongolia",
        "Switzerland",
        "Palestine",
        "Saudi Arabia",
        "Russia",
        "Kuwait",
        "Benin",
        "Brazil",
        "Poland",
        "Canada",
        "Bolivia",
        "Belarus",
        "Macedonia",
        "Azerbaijan",
        "Denmark",
        "Romania",
        "Nigeria",
        "Cote d'Ivoire",
        "Maldives",
        "Croatia",
        "Barbados",
        "Kenya",
        "Costa Rica",
        "Monaco",
        "Dominican Republic",
        "Pakistan",
        "South Africa",
        "Guinea",
        "Greece",
        "Trinidad and Tobago",
        "Norway",
        "France",
        "Guatemala",
        "Madagascar",
        "Armenia",
        "Saint Kitts and Nevis",
        "Rwanda",
        "Ireland",
        "Burundi",
        "Belize",
        "Bahamas",
        "Chile",
        "Dominica",
        "South Sudan",
        "Saint Vincent and the Grenadines",
        "Honduras",
        "Qatar",
        "Nepal",
        "Lesotho",
        "Italy",
        "San Marino",
        "Guinea-Bissau",
        "Vietnam",
        "Cuba",
        "El Salvador",
        "Hungary",
        "Bahrain",
        "Vatican",
        "Tanzania",
        "Ethiopia",
        "Eritrea",
        "Bosnia and Herzegovina",
    }
)
